Add support for dnsdist 1.9
PowerDNS/dnsdist-ansible pull request #117
Opened 2023-12-21 13:33 UTC by lpmhouben

Adding support for the dnsdist-19 repo was the easy part; fixing the molecule tests for Debian 11 and 12 was a lot more work.

2023-12-21 13:34 UTC, lpmhouben commented
(The ansible-lint error involves a spacing issue in, I shit you not, the .ansible-lint file. I haven't touched it)

2023-12-21 13:53 UTC, lpmhouben commented
Went in and cleared it up. Apparently YAML wants two spaces before an inline comment now.

2024-01-08 14:50 UTC, npmdnl commented on meta/main.yml
>          - jessie
```suggestion

```

2024-01-08 14:56 UTC, npmdnl commented on vars/main.yml
> +  yum_debug_symbols_repo_baseurl: http://repo.powerdns.com/centos/$basearch/$releasever/dnsdist-18/debug
```suggestion
  yum_debug_symbols_repo_baseurl: http://repo.powerdns.com/centos/$basearch/$releasever/dnsdist-19/debug
```

2024-01-08 16:24 UTC, npmdnl requested changes
Please have a look at the suggested changes.
Take note that `v1.9.0` has not been officially released yet

2024-01-09 17:40 UTC, lpmhouben commented
Thanks for the suggestions, they look good.

I'm headed out-of-country tomorrow evening; anything I haven't fixed before then won't be fixed for another week.

2024-04-05 15:29 UTC, npmdnl approved these changes

2024-04-08 14:10 UTC, npmdnl commented
Hello @lpmhouben in order to merge this push request you need to solve conflicting files and commit changes. TY

2025-07-31 09:42 UTC, closed without merging